### ISSUE TITLE
hello，how can i install this module for other python file? i try to "sudo python3 install setup.py install " ,howerver ,i can't use this module in other file

### ISSUE THREAD

**Issue by mouzougaai** [nasa/SMCPy#34]

**Comment by peleser** [comment]
Hi, I'd recommend cloning the source code and adding it to your Python path. If using a Unix-based system:
1. Navigate to directory where you want the source code to be: cd <path_to_directory>
2. git clone https://github.com/nasa/SMCPy.git
3. Add <path_to_directory>/SMCPy to your PYTHONPATH: export PYTHONPATH=$PYTHONPATH:<path_to_directory>/SMCPy
4. Import the module in your file using "from smcpy import <modules/classes>" (see examples in repo)

**Comment by peleser** [comment]
Note that SMCPy can now be installed using pip: https://pypi.org/project/smcpy/
