### ISSUE TITLE
Forecasting

### ISSUE THREAD

**Issue by waudinio27** [nasa/SMCPy#35]
I am looking for a SMC like this. Is is possible to forecast from the posterior? Or will you add it? This is what all particle filters are missing. Can you tell how this would work in practice? I cannot find information about it.

**Comment by peleser** [comment]
Hello,

You can propagate the posterior samples through your model of interest with whatever flavor of Monte Carlo simulation you'd like to use. I am not planning on writing any specific tools to support that as it would basically be a for loop over samples in the simplest case; for example:
```python
step, _ = smc.sample(1000, 10)
forecast_samples = [forecast_model(p) for p in step[-1].params]
```
There are more advanced methods for uncertainty propagation out there that accelerate convergence, etc. Hope that helps!

**Comment by waudinio27** [comment]
Thank you so much for your great answer. Amazing how you just wrote the loop by hand to show my some idea! I really love this :-D

**Comment by peleser** [comment]
One thing I should add -- the above code works if you are using the AdaptiveSampler class where the particles are reweighted at every step prior to the MCMC move. If you are using the FixedSampler class, you would need to weight the outputs according to the input weight. So if you wanted an expected value, for example, you'd need to do something more like:
```python
step, _ = smc.sample(1000, 10)
weighted_outputs= [forecast_model(p) * w for p, w in zip(step[-1].params, step[-1].weights)]
expected_value = sum(weighted_outputs)
```
I would recommend that you use the AdaptiveSampler unless you have a specific reason not to, however.

**Comment by waudinio27** [comment]
Hello peleser,

Thank you so much again! I was thinking by myself that a Sampler with
reweight would be better.
My idea in the end is to put the sampler on top of a Bayesian Tree
Regression. Like this I would also not have to transform the data to
extrapolate outside of the training data.

Just right now to see your solution it would even be best to use SMCPy in a
standalone fashion in one go. I have been a teacher for chemistry and
physics since a short time and I hope to have time to try it out in the
next holidays. Should not be a problem to install it with conda and plug in
proper data.

I was wondering how long your program will take to train a time series of
5000 values or even more? Just to have an idea. Did you try this?

Best regards and thanks again

Matthias


Am Mo., 20. März 2023 um 22:19 Uhr schrieb peleser ***@***.***

**Comment by peleser** [comment]
The run time will depend on the model you are using. If you vectorize computation in your model with [numpy](https://numpy.org/), you'll get a good amount of speedup using the [vectorized MCMC kernel](https://github.com/nasa/SMCPy/blob/main/smcpy/mcmc/vector_mcmc.py). I've tried to make the SMCPy overhead as small as possible.

**Comment by waudinio27** [comment]
Hello Peter,

I just found an article and will study it -

https://towardsdatascience.com/how-to-speedup-data-processing-with-numpy-vectorization-12acac71cfca

Best regards

Matthias

Am Do., 23. März 2023 um 14:19 Uhr schrieb Matthias Wiedemann <
***@***.***>:

**Comment by karthikncsuiisc** [comment]
Hello Matthias,

A good speedup with vectorized predictive simulations can be achieved.  Below is a research article that discusses the speedup achieved with vectorized simulation in SMC.

https://www.sciencedirect.com/science/article/pii/S0965997823000534?dgcid=author

https://www.sciencedirect.com/science/article/pii/S0965997823000534

Thank You
Karthik
